name: publish

on:
  workflow_dispatch:
    inputs: {}

env:
  DOTNET_ROLL_FORWARD: Major

jobs:
  build:
    uses: ./.github/workflows/template.yml
    name: build
    with:
      Directory: src/CloudTek.Sdk
      NetVersion: "8.0.100"
      Build:        true
      Pack:         true
      Push:         true
      NuGetApiUrl:  'https://api.nuget.org/v3/index.json'
    secrets:
      NuGetApiKey:  ${{ secrets.NUGET_API_KEY }}
